FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o /orchestrator ./cmd/orchestrator

FROM alpine:3.20
RUN addgroup -S secops && adduser -S -G secops secops
WORKDIR /orchestrator
COPY --from=builder /orchestrator /orchestrator
USER secops:secops
ENTRYPOINT ["/orchestrator","api"]
